version: '3'

services:
  app_test:
    container_name: full_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - mysql_test
    networks:
      - fullstack_test
    
  mysql_test:
    image: mysql:5.7
    container_name: full_db_test_mysql    
    ports: 
      - 3333:3306
    environment: 
      - MYSQL_DATABASE=${TestDbName}
      - MYSQL_USER=${TestDbUser}
      - MYSQL_PASSWORD=${TestDbPassword}
      - MYSQL_ROOT_PASSWORD=${TestDbPassword}
      - DATABASE_HOST=${TestDbHost} 
    volumes:
      - database_mysql_test:/var/lib/mysql
    networks:
      - fullstack_test
  
volumes:
  api_test:
  database_mysql_test:

networks:
  fullstack_test:
    driver: bridge
